name: Feature request
description: Suggest an idea for DigikamFS
labels: [enhancement]
body:
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: What are you trying to do? How do you use your photos (SMB, DLNA TV, Nextcloud, ...)?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
